config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'
  get 'sign-up', to: 'users#new'
  post 'sign-up', to: 'users#create'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories
  resources :articles
  resources :votes, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates_presence_of :title, :text, :image
  validates :title, :text, length: { minimum: 6 }
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'
  has_many :article_categories
  has_many :categories, through: :article_categories, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_one_attached :image
  validate :image_type
  validates_presence_of :categories

  def self.featured_article
    max_votes = 0
    result = Article.new
    articles = Article.all.includes(:votes)
    articles.each do |article|
      if article.votes.count > max_votes
        max_votes = article.votes.count
        result = article
      end
    end
    result
  end

  private

  def image_type
    errors.add(:image, 'is missing!') unless image.attached?

    errors.add(:image, 'needs to be a jpeg or png!') unless image.content_type.in?(%('image/jpeg image/png'))
  end
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :category
  belongs_to :article
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
end

app/models/user.rb
class User < ApplicationRecord
  validates_presence_of :name
  validates :name, uniqueness: true, length: { minimum: 3 }
  has_many :articles, foreign_key: 'user_id'
  has_many :votes
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?, :require_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !current_user.nil?
  end

  def require_user
    return if logged_in?

    flash[:danger] = 'You need to be logged in to perform that action'
    redirect_back fallback_location: root_path
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[edit update destroy]
  before_action :require_user, except: [:index]
  before_action :require_same_user, only: %i[edit update destroy]

  def index
    @featured_article = Article.featured_article
    @categories = Category.all.order(:priority).reverse_order
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.author = current_user
    if @article.save
      flash[:success] = 'Article was created successfully'
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @article.update(article_params)
      flash[:success] = 'Article was successfully updated'
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    flash[:danger] = 'Article was successfully deleted'
    redirect_back fallback_location: root_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :text, :image, category_ids: [])
  end

  def require_same_user
    return if current_user == @article.author || current_user.admin?

    flash[:danger] = 'You can only edit or delete your own article'
    redirect_back fallback_location: root_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin_user, except: [:show]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = 'Category was created successfully'
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def show
    @category = Category.find(params[:id])
    @articles = @category.articles.order(created_at: :desc)
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = 'Category was successfully updated'
      redirect_to categories_path
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    flash[:danger] = 'Category was successfully deleted'
    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name, :priority)
  end

  def require_admin_user
    return if logged_in? && current_user.admin?

    flash[:danger] = 'You need admin access to perform that action'
    redirect_to root_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(name: params[:session][:name])
    if user
      session[:user_id] = user.id
      flash[:success] = 'You have successfully logged in'
      redirect_to root_path
    else
      flash.now[:danger] = 'There was something wrong with your login information'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'You have successfully logged out'
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'You have successfully created your account'
      redirect_to root_path
    else
      flash.now[:danger] = 'There was something wrong with your sign up information'
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :require_user

  def create
    @vote = current_user.votes.new(article_id: params[:article_id])

    if @vote.save
      flash[:success] = 'You voted an article.'
    else
      flash[:danger] = 'You cannot vote this article.'
    end
    redirect_back fallback_location: root_path
  end

  def destroy
    vote = Vote.find_by(id: params[:id], user: current_user, article_id: params[:article_id])
    if vote
      vote.destroy
      flash[:success] = 'You unvoted an article.'
    else
      flash[:danger] = 'You cannot unvoted an article that you did not vote before.'
    end
    redirect_back fallback_location: root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def menu_link_to(link_text, link_path)
    class_name = current_page?(link_path) ? 'menu-item active' : 'menu-item'

    content_tag(:div, class: class_name) do
      link_to link_text, link_path
    end
  end

  def vote_or_unvote_btn(article)
    vote = Vote.find_by(article: article, user: current_user)
    if vote
      link_to('Unvote!', vote_path(id: vote.id, article_id: article.id), method: :delete)
    else
      link_to('Vote!', votes_path(article_id: article.id), method: :post)
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/edit.html.erb
<div class="row">
  <div class="col-md-6 mx-auto">
    <h3>Edit Article</h3>
    <%= form_for(@article) do |f| %>
      <%= render 'shared/error_messages' %>
      <div class = "form-group">
        <%= f.label :title, "Title" %>
        <%= f.text_field :title, placeholder: "Enter title of article", class: 'form-control' %>
      </div>
      <div class = "form-group">
        <%= f.label :text, "Body" %>
        <%= f.text_area :text, rows: 10, placeholder: "Enter article body", class: 'form-control' %>
      </div>
      <div class = "form-group">
        <%= f.label :image %>
        <%= f.file_field :image, placeholder: "Upload image", required: true, class: 'form-control' %>
      </div>
      <div class = "form-group">
        <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
          <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text } %>
        <% end %>
      </div>
      <div class="form-group">
        <%= f.submit "Submit", class: "btn btn-primary" %>
      </div>
      
    <% end %>
  </div>
</div>

app/views/articles/index.html.erb
<div class="featured" style="background-image: url('<%= url_for(@featured_article.image) if @featured_article.image.attached? %>');"  >
  <div class="featured_title">
    <h5><%= @featured_article.title %></h5>
  </div>
</div>


<div class="d-flex" style="height: 20vh;">

	<% @categories.each do |category| %>
	<% unless category.articles.last.nil? %>
		<div class="card vh-30 categories"
		     style="background-image: url('<%= url_for(category.articles.last.image) if category.articles.last.image.attached? %>');">
		  <div>
		    <h5 class="m-1"><%= link_to category.name, category_path(category), class: "text-white" %></h5>
		  </div>
		  <div class="article-title">
		    <p class="text-white"><%= category.articles.last.title %></p>
		  </div>
		</div>
	<% end %>
	<% end %>
</div>

app/views/articles/new.html.erb
<div class="row">
  <div class="col-md-6 mx-auto">
    <h3>Create New Article</h3>
    <%= form_for(@article) do |f| %>
      <%= render 'shared/error_messages' %>
      <div class = "form-group">
        <%= f.label :title, "Title" %>
        <%= f.text_field :title, placeholder: "Enter title of article", class: 'form-control' %>
      </div>
      <div class = "form-group">
        <%= f.label :text, "Body" %>
        <%= f.text_area :text, rows: 10, placeholder: "Enter article body", class: 'form-control' %>
      </div>
      <div class = "form-group">
        <%= f.label :image %>
        <%= f.file_field :image, placeholder: "Upload image", required: true, class: 'form-control' %>
      </div>
      <div class = "form-group">
        <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
          <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text } %>
        <% end %>
      </div>
      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/categories/edit.html.erb
<div class="row">
  <div class="col-md-6 mx-auto">
    <h3>Edit Category</h3>
    <%= form_for(@category) do |f| %>
      <div class = "form-group">
        <%= f.label :name, "Name" %>
        <%= f.text_field :name, placeholder: "Enter name of Category", class: 'form-control', required: true %>
      </div>
      <div class = "form-group">
        <%= f.label :priority, "Priority(between 1 and 5)" %>
        <%= f.number_field :priority, rows: 10, placeholder: "Enter priority of category", class: 'form-control', min: 1, max: 5, required: true %>
      </div>
      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/categories/index.html.erb
<div class="row">
	<div class="col-md-6 mx-auto">
		<h3>Categories</h3>
		<% @categories.each do |category| %>
			<div>
				<%= category.name %> 
				<%= category.priority %> 
				<%= link_to 'Edit', edit_category_path(category) %> 
				<%= link_to 'Delete', category_path(category), method: :delete,
													data: { confirm: "Are you sure you want to delete this category?"} %>
			</div>
		<% end %>
		<%= link_to 'Create New Category', new_category_path %>
	</div>

</div>

app/views/categories/new.html.erb
<div class="row">
  <div class="col-md-6 mx-auto">
    <h3>Create New Category</h3>
    <%= form_for(@category) do |f| %>
      <div class = "form-group">
        <%= f.label :name, "Name" %>
        <%= f.text_field :name, placeholder: "Enter name of Category", class: 'form-control', required: true %>
      </div>
      <div class = "form-group">
        <%= f.label :priority, "Priority(between 1 and 5)" %>
        <%= f.number_field :priority, rows: 10, placeholder: "Enter priority of category", class: 'form-control', min: 1, max: 5, required: true %>
      </div>
      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/categories/show.html.erb
<div class="d-flex w-100 flex-wrap vh-100 align-content-start">
<% @articles.each do |article| %>
	<div class="d-flex w-50 pb-1">
		<div class="w-50">
			<%= image_tag article.image, class: "w-100 h-100" if article.image.attached? %>
		</div>
		<div class="w-50 bg-light d-flex flex-column justify-content-between">
			<div class="p-2">
				<h4 class="category-title text-info">
					<%= @category.name %>
				</h4>
				<h5>
					<%= article.title %>
				</h5>
				<div class="p-0">
					<%= truncate(article.text, length: 100) %>
				</div>
			</div>
			<div>
				<div class="pl-2">
					<span class="badge badge-info">
						Author: <%= article.author.name %>
					</span>
					<span class="badge badge-info">
						<a href="#" class="text-white">Read More</a>
					</span>	
				</div>
				<div class="pl-2">
					<span class="badge badge-warning">
						<%= vote_or_unvote_btn(article) %>
					</span>
					<% if logged_in? && (current_user == article.author || current_user.admin?) %>
						<span class="badge badge-warning">
							<%= link_to 'Edit', edit_article_path(article) %>
						</span>
						<span class="badge badge-warning">
							<%= link_to 'Delete', article_path(article), method: :delete,
													data: { confirm: "Are you sure you want to delete the article?"} %>
						</span>
					<% end %>
				</div>	
			</div>			
		</div>	
	</div>
	
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RorCapstone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navigation' %>
    <div class="container mt-5 pt-5 mb-5 pb-5">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %> 
       
      <%= yield %>
    </div>

    <%= render 'shared/footer' %>  
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @article.errors.any? %>
  <div>
    <div class="alert alert-danger">
      The form contains <%= pluralize(@article.errors.count, "error") %>.
    </div>
    <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="navbar fixed-bottom navbar-expand-lg navbar-light bg-light w-100">
  <a class="navbar-brand" href="#">ChessStyle</a>

  <div class="collapse navbar-collapse">
    <ul class="navbar-nav mr-auto ml-auto">
      <li class="nav-item">
        <a href="#" class="nav-link">Privacy Policy</a>
      </li>
      <li class="nav-item">
        <a href="#" class="nav-link">Terms & Conditions</a>
      </li>
    </ul>
    <div>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a href="#" class="nav-link">Connect with us: </a>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link">
            <%= fa_stacked_icon "twitter", base: "square-o" %>
          </a>
        </li>  
        <li class="nav-item">
          <a href="#" class="nav-link">
            <%= fa_stacked_icon "instagram", base: "square-o" %>
          </a>
        </li>    
        <li class="nav-item">
          <a href="#" class="nav-link">
            <%= fa_stacked_icon "facebook", base: "square-o" %>
          </a>
        </li>    
      </ul>
    </div> 
  </div>
</footer>

app/views/shared/_navigation.html.erb
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">ChessStyle</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto ml-auto">
      <li class="nav-item">
        <%= link_to 'Home', root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Write an Article', new_article_path, class: "nav-link" %>
      </li>
      <% if logged_in? && current_user.admin? %>
        <li class="nav-item">
          <%= link_to 'Categories', categories_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    <div>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <% if logged_in? %>
            <%= link_to 'LOGOUT', logout_path, class: "nav-link", method: :delete %>
          <% else %>
            <%= link_to 'LOGIN', login_path, class: "nav-link" %>
            <li class="nav-item">
              <%= link_to 'REGISTER', sign_up_path, class: "nav-link" %>
            </li>  
          <% end %>
        </li>
        <li class="nav-item">
          <% if logged_in? && current_user.admin? %>
            <span class="badge badge-info align-bottom mt-2">Admin</span>
          <% end %>
        </li>        
      </ul>
    </div>
    
  </div>
</nav>

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-6 mx-auto">
    <h3>Register</h3>
    <%= form_for(@user,  url: sign_up_path) do |f| %>
      <div class = "form-group">
        <%= f.label :name, "Name" %>
        <%= f.text_field :name, placeholder: "Enter username", class: 'form-control' %>
      </div>
      <%= f.button "Register", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>